prod:
  prod_code: "res/Western-Biologics Part Number to ProdCode.xlsx"
  pdf_output_dir:
    - 'Z:\Private\arvin.asgharian\CoAs'
    - 'Z:\Private\arvin.asgharian\Coa2'
    - './output/'
  mapping_output_dir:
    - 'Z:\Private\arvin.asgharian\mapping'
    - './output/'
  model_dir: "res/models"
  mapping_dir: "res/mappings"
  models:
    CE-SDS:
      template: "046-317 CofA_Maurice-CE-SDS_Cartridge_090-100_revE.pdf"
      fields: "fields.yaml"
      mapping: "coa_mapping_cief_400_template.csv"
    'cIEF 200':
      template: "046-329_CofA_Maurice_cIEF_Cartridge_090-101_RevF.pdf"
      fields: "fields.yaml"
      mapping: "coa_mapping_template.csv"
  file_perm:
    "print": true
    "modify": false        
    "copy": true
    "form_fill": false     
    "annotate": false
    "form_fill": false
    "accessibility": true        
    "assemble": false         
    "extract": false
  def_mapping_columns: "res/mapping_columns.json"

