prod:
  code_map: res/codes.json
  file_perm:
    accessibility: true
    annotate: false
    assemble: false
    copy: true
    extract: false
    form_fill: false
    modify: false
    print: true
  font: Helv
  fontsize: 8
  mapping_columns: res/mapping_columns.json
  mapping_dir: res/mappings
  mapping_output_dir:
  - ./output/
  model_dir: res/models
  models:
  - SDS+
  - SDSTurbo
  - cIEF 200
  - CE-SDS
  - CE-SDS 50
  - Flex
  - cIEF 400
  pdf_output_dir:
  - ./output/
  prod_code_map: res/Western-Biologics Part Number to ProdCode.xlsx
  profile: profile.yaml
test:
  code_map: res/codes.json
  file_perm:
    accessibility: true
    annotate: false
    assemble: false
    copy: true
    extract: false
    form_fill: false
    modify: false
    print: true
  font: Helv
  fontsize: 8
  mapping_columns: res/mapping_columns.json
  mapping_dir: res/mappings
  mapping_output_dir:
  - ./src/tests/output/
  model_dir: res/models
  models:
  - SDS+
  - SDSTurbo
  - cIEF 200
  - CE-SDS
  - CE-SDS 50
  - Flex
  - cIEF 400
  pdf_output_dir:
  - ./src/tests/output/
  prod_code_map: res/Western-Biologics Part Number to ProdCode.xlsx
  profile: profile.yaml
  test_coa_exp_dir: ./tests/res
