prod:
  def_mapping_columns: res/mapping_columns.json
  default_fields: fields.yaml
  file_perm:
    accessibility: true
    annotate: false
    assemble: false
    copy: true
    extract: false
    form_fill: false
    modify: false
    print: true
  mapping_dir: res/mappings
  mapping_output_dir:
  - Z:/Private/arvin.asgharian/mapping
  model_dir: res/models
  models:
    CE-SDS:
      mapping: coa_mapping_cief_400_template.csv
      template: 046-317 CofA_Maurice-CE-SDS_Cartridge_090-100_revE.pdf
    SDS+:
      mapping: coa_mapping_flex.csv
      template: Q51-0003_CofA_090-157_Maurice-CE-SDS_PLUS_Cartridge_RevD.pdf
    cIEF 200:
      fields: fields.yaml
      mapping: coa_mapping_template.csv
      template: 046-329_CofA_Maurice_cIEF_Cartridge_090-101_RevF.pdf
  pdf_output_dir:
  - Z:/Private/arvin.asgharian/CoAs
  - Z:/Private/arvin.asgharian/Coa2
  prod_code_map: res/Western-Biologics Part Number to ProdCode.xlsx
test:
  def_mapping_columns: res/mapping_columns.json
  default_fields: fields.yaml
  file_perm:
    accessibility: true
    annotate: false
    assemble: false
    copy: true
    extract: false
    form_fill: false
    modify: false
    print: true
  mapping_dir: res/mappings
  mapping_output_dir:
  - ./output/
  model_dir: res/models
  models:
    SDS+:
      PN: 090-157
      fields: fields.yaml
      template: Q51-0003_CofA_090-157_Maurice-CE-SDS_PLUS_Cartridge_RevD.pdf
    SDSTurbo:
      PN: 101-0058
      fields: fields.yaml
      template: Q51-0194_CofA_101-0058_Cartridge, Maurice Turbo CE-SDS_REVB.pdf
    cIEF 200:
      PN: 090-101
      mapping: coa_mapping_template.csv
      template: 046-329_CofA_Maurice_cIEF_Cartridge_090-101_RevF.pdf
  pdf_output_dir:
  - ./output/
  prod_code_map: res/Western-Biologics Part Number to ProdCode.xlsx
