name: Build and Release CL Tool (windows)

on:
  push:
    tags:
      - 'v*'
    branches:
      - prod
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r automation/pyREQ.txt

      - name: Build using PyInstaller
        shell: pwsh
        run: ./buildPy.ps1
      
      - name: Zip CLI Tool
        shell: pwsh
        run: |
            Compress-Archive -Path automation/dist/main/* -DestinationPath cli_tool.zip

      - name: Build Tauri App
        shell: pwsh
        run: |
          cd coat-ui
          npm install
          npm run tauri build

      - name: Upload NSIS Installer and CLI Tool
        uses: softprops/action-gh-release@v2
        with:
          files: |
            coat-ui/src-tauri/target/release/bundle/nsis/*.exe
            cli_tool.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
